"""Add tenant_id and initial schema

Revision ID: 2571a5c18930
Revises: 
Create Date: 2026-08-30 06:57:09.510237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '2571a5c18930'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('source_doc', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_chunks_id'), 'knowledge_base_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_chunks_source_doc'), 'knowledge_base_chunks', ['source_doc'], unique=False)
    op.create_index(op.f('ix_knowledge_base_chunks_tenant_id'), 'knowledge_base_chunks', ['tenant_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('instagram_handle', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('service_requested', sa.String(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('budget_estimate', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_name'), 'leads', ['name'], unique=False)
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_table('tenant_configs',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('whatsapp_verify_token', sa.String(), nullable=True),
    sa.Column('whatsapp_access_token', sa.String(), nullable=True),
    sa.Column('whatsapp_phone_number_id', sa.String(), nullable=True),
    sa.Column('instagram_verify_token', sa.String(), nullable=True),
    sa.Column('instagram_access_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_index(op.f('ix_tenant_configs_tenant_id'), 'tenant_configs', ['tenant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('service_scope', sa.Text(), nullable=False),
    sa.Column('estimated_price', sa.String(), nullable=False),
    sa.Column('estimated_timeline', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_id'), 'proposals', ['id'], unique=False)
    op.create_index(op.f('ix_proposals_lead_id'), 'proposals', ['lead_id'], unique=False)
    op.create_index(op.f('ix_proposals_tenant_id'), 'proposals', ['tenant_id'], unique=False)
    op.create_table('tool_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_call_logs_id'), 'tool_call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_tool_call_logs_tenant_id'), 'tool_call_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tool_call_logs_tool_name'), 'tool_call_logs', ['tool_name'], unique=False)
    op.create_table('followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_id'), 'followups', ['id'], unique=False)
    op.create_index(op.f('ix_followups_lead_id'), 'followups', ['lead_id'], unique=False)
    op.create_index(op.f('ix_followups_tenant_id'), 'followups', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_followups_tenant_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_lead_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_id'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_tool_call_logs_tool_name'), table_name='tool_call_logs')
    op.drop_index(op.f('ix_tool_call_logs_tenant_id'), table_name='tool_call_logs')
    op.drop_index(op.f('ix_tool_call_logs_id'), table_name='tool_call_logs')
    op.drop_table('tool_call_logs')
    op.drop_index(op.f('ix_proposals_tenant_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_lead_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_tenant_configs_tenant_id'), table_name='tenant_configs')
    op.drop_table('tenant_configs')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_knowledge_base_chunks_tenant_id'), table_name='knowledge_base_chunks')
    op.drop_index(op.f('ix_knowledge_base_chunks_source_doc'), table_name='knowledge_base_chunks')
    op.drop_index(op.f('ix_knowledge_base_chunks_id'), table_name='knowledge_base_chunks')
    op.drop_table('knowledge_base_chunks')
    # ### end Alembic commands ###
